name: GitHub Actions Deploy Demo
run-name: ${{ github.actor }} GitHub Actions è‡ªå‹•éƒ¨ç½² ğŸš€
on:
  push:
    tags:
      - "v*" # åªæœ‰ç•¶ tag åç¨±ä»¥ 'ver' é–‹é ­æ™‚è§¸ç™¼
jobs:
  autoDeploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: åˆå§‹åŒ–å°ˆæ¡ˆ
        run: |
          npm install
      - name: æ‰“åŒ…å°ˆæ¡ˆ
        run: |
          npm run build
      - name: å­˜æ”¾æ‰“åŒ…å¾Œçš„å°ˆæ¡ˆä¸¦æº–å‚™ä¸Šå‚³
        uses: actions/upload-artifact@v2
        with:
          name: my-artifact
          path: dist
          if-no-files-found: error # 'warn' or 'ignore' are also available, defaults to `warn`
      - name: å°å‡ºç›®å‰å·¥ä½œç’°å¢ƒçš„è³‡æ–™å¤¾çµæ§‹
        run: |
          ls ${{ github.workspace }}
      - name: éƒ¨ç½²ç”Ÿæˆçš„æª”æ¡ˆåˆ° gh_page åˆ†æ”¯
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: dist
          PUBLISH_BRANCH: gh-pages
          full_commit_message: ${{ github.event.head_commit.message }}
      - run: echo "è‡ªå‹•æ‰“åŒ…éƒ¨ç½²çµæœ ${{ job.status }}"
